[install]
# Prefer exact versions for stability
save-exact = true
registry = "https://registry.npmjs.org/"

[test]
# Use Bun's test runner
preload = ["./test/bun-setup.js"]
timeout = 5000 # timeout in milliseconds (example: 5000ms = 5s)
coverageSkipTestFiles = true
coveragePathIgnorePatterns = "test/helpers/**/*.js"

[run]
# Enable Bun's built-in bundler for imports
bun = true

